package dev.git.ua.EntertainmentNetworkServer.Models;
// Generated Feb 9, 2018 5:32:55 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.*;

/**
 * Hall generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType
@Entity
@Table(name = "HALL", schema = "TEST")
public class Hall extends BaseModel implements java.io.Serializable
{
	public Hall()
	{
	}
	
	public Hall(BigDecimal halId)
	{
		this.id = halId;
	}
	
	public Hall(BigDecimal halId, Cinema cinema, String halName)
	{
		this.id = halId;
		this.cinema = cinema;
		this.name = halName;
	}

	public Hall(BigDecimal halId, Cinema cinema, String halName, Set<Section> sections,
			Set<Scheduler> schedulers) 
	{
		this(halId, cinema, halName);
		this.sections = sections;
		this.schedulers = schedulers;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "HALL_SEQ")
    @SequenceGenerator(name = "HALL_SEQ", sequenceName = "HALL_SEQ", allocationSize = 1)
	@Column(name = "HAL_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getHalId()
	{
		return this.id;
	}

	public void setHalId(BigDecimal halId)
	{
		this.id = halId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "HAL_CIN_ID", nullable=false)
	public Cinema getCinema()
	{
		return this.cinema;
	}

	public void setCinema(Cinema cinema)
	{
		this.cinema = cinema;
	}

	@Column(name = "HAL_NAME", nullable = false, length = 100)
	public String getHalName()
	{
		return this.name;
	}

	public void setHalName(String halName)
	{
		this.name = halName;
	}

	@OneToMany(cascade = CascadeType.ALL, fetch = FetchType.EAGER, mappedBy = "hall", orphanRemoval = true )
	public Set<Section> getSections()
	{
		
		for(Section sect : this.sections)
		{
			if(sect.getHall() == null)
			{
				sect.setHall(this);
			}
		}
		
		return this.sections;
	}

	public void setSections(Set<Section> sections)
	{
		this.sections = sections;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "hall")
	public Set<Scheduler> getSchedulers()
	{
		return this.schedulers;
	}

	public void setSchedulers(Set<Scheduler> schedulers) 
	{
		this.schedulers = schedulers;
	}
	
	@XmlTransient
	private Cinema cinema;
	private Set<Section> sections = new HashSet<Section>(0);
	@XmlTransient
	private Set<Scheduler> schedulers = new HashSet<Scheduler>(0);
}
