package dev.git.ua.EntertainmentNetworkServer.Models;
// Generated Mar 14, 2018 11:11:06 AM by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlTransient;
import javax.xml.bind.annotation.XmlType;

/**
 * Scheduler generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType
@Entity
@Table(name = "SCHEDULER", schema = "TEST")
public class Scheduler extends BaseModel implements java.io.Serializable 
{
	public Scheduler() 
	{
	}

	public Scheduler(BigDecimal schId)
	{
		this.id = schId;
	}
	
	public Scheduler(BigDecimal schId, Hall hall, Show show, String schName, String schDescr) 
	{
		this(schId);
		this.name = schName;
		this.hall = hall;
		this.show = show;
		this.schDescr = schDescr;
	}

	public Scheduler(BigDecimal schId, Hall hall, Show show, String schName, String schDescr, Date schTimeFrom, Date schTimeTo,
			Set<Tickets> ticketses) 
	{
		this(schId, hall, show, schName, schDescr);		
		this.schTimeFrom = schTimeFrom;
		this.schTimeTo = schTimeTo;
		this.ticketses = ticketses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SCH_SEQ")
    @SequenceGenerator(name = "SCH_SEQ", sequenceName = "SCH_SEQ")
	@Column(name = "SCH_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSchId()
	{
		return this.id;
	}

	public void setSchId(BigDecimal schId)
	{
		this.id = schId;
	}

	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCH_HAL_ID", nullable = false)
	public Hall getHall() 
	{
		return this.hall;
	}

	public void setHall(Hall hall)
	{
		this.hall = hall;
	}
	
	@Transient
	@XmlElement
	public BigDecimal getHallId()
	{
		return this.getHall() == null ? null : this.getHall().getHalId();
	}
	
	public void setHallId(BigDecimal id)
	{
		this.setHall(new Hall(id));
	}
	
	@ManyToOne(fetch = FetchType.LAZY)
	@JoinColumn(name = "SCH_SHW_ID", nullable = false)
	public Show getShow()
	{	
		return this.show;
	}

	public void setShow(Show show) 
	{
		this.show = show;
	}
	
	@Column(name = "SCH_NAME", nullable = false, length = 100)
	public String getSchName() 
	{
		return this.name;
	}

	public void setSchName(String schName) 
	{
		this.name = schName;
	}

	@Column(name = "SCH_DESCR")
	public String getSchDescr() 
	{
		return this.schDescr;
	}

	public void setSchDescr(String schDescr) 
	{
		this.schDescr = schDescr;
	}
	
	@Transient
	@XmlElement
	public BigDecimal getShowId()
	{
		return this.getShow() == null ? null : this.getShow().getShwId();
	}
	
	public void setShowId(BigDecimal id)
	{
		this.setShow(new Show(id));
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SCH_TIME_FROM", length = 7)
	public Date getSchTimeFrom() 
	{
		return this.schTimeFrom;
	}

	public void setSchTimeFrom(Date schTimeFrom)
	{
		this.schTimeFrom = schTimeFrom;
	}

	@Temporal(TemporalType.TIMESTAMP)
	@Column(name = "SCH_TIME_TO", length = 7)
	public Date getSchTimeTo() 
	{
		return this.schTimeTo;
	}

	public void setSchTimeTo(Date schTimeTo)
	{
		this.schTimeTo = schTimeTo;
	}
	
	@Column(name = "SCH_COEF", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSchCoef() 
	{
		return schCoef;
	}

	public void setSchCoef(BigDecimal schCoef) 
	{
		this.schCoef = schCoef;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "scheduler")
	public Set<Tickets> getTicketses() 
	{
		return this.ticketses;
	}

	public void setTicketses(Set<Tickets> ticketses) 
	{
		this.ticketses = ticketses;
	}
	

	@XmlTransient
	private Hall hall;
	@XmlTransient
	private Show show;
	private String schDescr;
	private Date schTimeFrom;
	private Date schTimeTo;
	private BigDecimal schCoef;	
	@XmlTransient
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);
}
