package dev.git.ua.EntertainmentNetworkServer.Models;
// Generated Feb 9, 2018 5:32:55 PM by Hibernate Tools 3.5.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.*;

/**
 * Seat generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType
@Entity
@Table(name = "SEAT", schema = "TEST")
public class Seat extends BaseModel implements java.io.Serializable
{	
	public Seat() 
	{
	}
	
	public Seat(BigDecimal seatId)
	{
		this.id = seatId;
	}

	public Seat(BigDecimal seatId, Section section, int seatNum, int seatColumn, int seatRow, int seatType, boolean seatIsactive) 
	{
		this.id = seatId;
		this.section = section;
		this.seatNum = seatNum;
		this.seatColumn = seatColumn;
		this.seatRow = seatRow;
		this.seatType = seatType;
		this.seatIsactive = seatIsactive;
	}

	public Seat(BigDecimal seatId, Section section, int seatNum, int seatColumn, int seatRow, int seatType, boolean seatIsactive,
			Set<Tickets> ticketses) 
	{
		this(seatId, section, seatNum, seatColumn, seatRow, seatType, seatIsactive);		
		this.ticketses = ticketses;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEAT_SEQ")
    @SequenceGenerator(name = "SEAT_SEQ", sequenceName = "SEAT_SEQ", allocationSize = 1)
	@Column(name = "SEAT_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSeatId()
	{
		return this.id;
	}

	public void setSeatId(BigDecimal seatId)
	{
		this.id = seatId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SEAT_SEC_ID", nullable = false)
	public Section getSection() 
	{
		return this.section;
	}

	public void setSection(Section section) 
	{
		this.section = section;
	}

	@Column(name = "SEAT_COLUMN", nullable = false, precision = 22, scale = 0)
	public int getSeatColumn()
	{
		return this.seatColumn;
	}

	public void setSeatColumn(int seatColumn)
	{
		this.seatColumn = seatColumn;
	}
	
	@Column(name = "SEAT_NUM", nullable = false, precision = 22, scale = 0)
	public int getSeatNum()
	{
		return this.seatNum;
	}

	public void setSeatNum(int seatNum)
	{
		this.seatNum = seatNum;
	}

	@Column(name = "SEAT_ROW", nullable = false, precision = 22, scale = 0)
	public int getSeatRow()
	{
		return this.seatRow;
	}

	public void setSeatRow(int seatRow)
	{
		this.seatRow = seatRow;
	}

	@Column(name = "SEAT_TYPE", nullable = false, precision = 22, scale = 0)
	public int getSeatType() 
	{
		return this.seatType;
	}

	public void setSeatType(int seatType) 
	{
		this.seatType = seatType;
	}
	
	@Column(name = "SEAT_ISACTIVE", nullable = false, precision = 1, scale = 0)
	public boolean getSeatIsactive() 
	{
		return this.seatIsactive;
	}

	public void setSeatIsactive(boolean seatIsactive)
	{
		this.seatIsactive = seatIsactive;
	}

	@OneToMany(fetch = FetchType.LAZY, mappedBy = "seat")
	public Set<Tickets> getTicketses() 
	{
		return this.ticketses;
	}

	public void setTicketses(Set<Tickets> ticketses) 
	{
		this.ticketses = ticketses;
	}
	
	@XmlTransient
	private Section section;
	private boolean seatIsactive;
	private int seatColumn;
	private int seatNum;
	private int seatRow;
	private int seatType;
	@XmlTransient
	private Set<Tickets> ticketses = new HashSet<Tickets>(0);
}
