package dev.git.ua.EntertainmentNetworkServer.Models;
// Generated Mar 14, 2018 11:11:06 AM by Hibernate Tools 3.6.0.Final

import java.math.BigDecimal;
import java.util.HashSet;
import java.util.Set;
import javax.persistence.*;
import javax.xml.bind.annotation.*;

/**
 * Floor generated by hbm2java
 */
@SuppressWarnings("serial")
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType
@Entity
@Table(name = "SECTION", schema = "TEST")
public class Section extends BaseModel implements java.io.Serializable
{
	public Section()
	{
	}

	public Section(BigDecimal secId)
	{
		this.id = secId;
	}
	
	public Section(BigDecimal secId, Hall hall, BigDecimal secCoef) 
	{
		this.id = secId;
		this.hall = hall;
		this.secCoef = secCoef;
	}

	public Section(BigDecimal secId, Hall hall, String secName, BigDecimal secCoef, Set<Seat> seats) 
	{
		this(secId, hall, secCoef);
		this.name = secName;
		this.seats = seats;
	}

	@Id
	@GeneratedValue(strategy = GenerationType.SEQUENCE, generator = "SEC_SEQ")
    @SequenceGenerator(name = "SEC_SEQ", sequenceName = "SEC_SEQ", allocationSize = 1)
	@Column(name = "SEC_ID", unique = true, nullable = false, precision = 22, scale = 0)
	public BigDecimal getSecId() 
	{
		return this.id;
	}

	public void setSecId(BigDecimal secId) 
	{
		this.id = secId;
	}

	@ManyToOne(fetch = FetchType.EAGER)
	@JoinColumn(name = "SEC_HAL_ID", nullable = false)
	public Hall getHall() 
	{
		return this.hall;
	}

	public void setHall(Hall hall) 
	{
		this.hall = hall;
	}

	@Column(name = "SEC_NAME", length = 100)
	public String getSecName() 
	{
		return this.name;
	}

	public void setSecName(String secName) 
	{
		this.name = secName;
	}
	
	@Column(name = "SEC_COEF", nullable = false, precision = 22, scale = 0)
	public BigDecimal getSecCoef()
	{
		return this.secCoef;
	}

	public void setSecCoef(BigDecimal secCoef)
	{
		this.secCoef = secCoef;
	}

	@OneToMany(fetch = FetchType.EAGER, mappedBy = "section", cascade = CascadeType.ALL, orphanRemoval = true)
	public Set<Seat> getSeats() 
	{		
		for(Seat seat : this.seats)
		{
			if(seat.getSection() == null)
			{
				seat.setSection(this);
			}
		}
		
		return this.seats;
	}

	public void setSeats(Set<Seat> seats) 
	{
		this.seats = seats;
	}	   

	private BigDecimal secCoef;
	@XmlTransient
	private Hall hall;
	private Set<Seat> seats = new HashSet<Seat>(0);
}
