//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.TicketService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class TicketSoldException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", ConfigurationName="TicketService.TicketService")]
    public interface TicketService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/removeTicketRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/removeTicketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EntertainmentNetwork.DAL.TicketService.ServiceException), Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/removeTicket/Fault/ServiceException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetwork.DAL.TicketService.removeTicketResponse removeTicket(EntertainmentNetwork.DAL.TicketService.removeTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/removeTicketRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/removeTicketResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.removeTicketResponse> removeTicketAsync(EntertainmentNetwork.DAL.TicketService.removeTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.TicketService.getTicketsResponse getTickets(EntertainmentNetwork.DAL.TicketService.getTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.getTicketsResponse> getTicketsAsync(EntertainmentNetwork.DAL.TicketService.getTicketsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/saveTicketsRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/saveTicketsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.TicketService.saveTicketsResponse saveTickets(EntertainmentNetwork.DAL.TicketService.saveTicketsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/saveTicketsRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/saveTicketsResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.saveTicketsResponse> saveTicketsAsync(EntertainmentNetwork.DAL.TicketService.saveTicketsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsByScheduleIDRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsByScheduleIDResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDResponse getTicketsByScheduleID(EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsByScheduleIDRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/getTicketsByScheduleIDResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDResponse> getTicketsByScheduleIDAsync(EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/generateTicketRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/generateTicketResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EntertainmentNetwork.DAL.TicketService.TicketSoldException), Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/generateTicket/Fault/TicketSoldException", Name="TicketSoldException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.TicketService.generateTicketResponse generateTicket(EntertainmentNetwork.DAL.TicketService.generateTicketRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/generateTicketRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/generateTicketResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.generateTicketResponse> generateTicketAsync(EntertainmentNetwork.DAL.TicketService.generateTicketRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/findTicketByIdRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/findTicketByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.TicketService.findTicketByIdResponse findTicketById(EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/findTicketByIdRequest", ReplyAction="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/TicketService" +
            "/findTicketByIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.findTicketByIdResponse> findTicketByIdAsync(EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeTicket", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeTicketRequest() {
        }
        
        public removeTicketRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeTicketResponse", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeTicketResponse {
        
        public removeTicketResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class tickets : baseModel {
        
        private scheduler schedulerField;
        
        private seat seatField;
        
        private decimal tctPriceField;
        
        private bool tctPriceFieldSpecified;
        
        private bool tctIssoldField;
        
        private decimal ordersIdField;
        
        private bool ordersIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public scheduler scheduler {
            get {
                return this.schedulerField;
            }
            set {
                this.schedulerField = value;
                this.RaisePropertyChanged("scheduler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public seat seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
                this.RaisePropertyChanged("seat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal tctPrice {
            get {
                return this.tctPriceField;
            }
            set {
                this.tctPriceField = value;
                this.RaisePropertyChanged("tctPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tctPriceSpecified {
            get {
                return this.tctPriceFieldSpecified;
            }
            set {
                this.tctPriceFieldSpecified = value;
                this.RaisePropertyChanged("tctPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool tctIssold {
            get {
                return this.tctIssoldField;
            }
            set {
                this.tctIssoldField = value;
                this.RaisePropertyChanged("tctIssold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal ordersId {
            get {
                return this.ordersIdField;
            }
            set {
                this.ordersIdField = value;
                this.RaisePropertyChanged("ordersId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordersIdSpecified {
            get {
                return this.ordersIdFieldSpecified;
            }
            set {
                this.ordersIdFieldSpecified = value;
                this.RaisePropertyChanged("ordersIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class scheduler : baseModel {
        
        private string schDescrField;
        
        private System.DateTime schTimeFromField;
        
        private bool schTimeFromFieldSpecified;
        
        private System.DateTime schTimeToField;
        
        private bool schTimeToFieldSpecified;
        
        private decimal schCoefField;
        
        private bool schCoefFieldSpecified;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        private decimal showIdField;
        
        private bool showIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string schDescr {
            get {
                return this.schDescrField;
            }
            set {
                this.schDescrField = value;
                this.RaisePropertyChanged("schDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime schTimeFrom {
            get {
                return this.schTimeFromField;
            }
            set {
                this.schTimeFromField = value;
                this.RaisePropertyChanged("schTimeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeFromSpecified {
            get {
                return this.schTimeFromFieldSpecified;
            }
            set {
                this.schTimeFromFieldSpecified = value;
                this.RaisePropertyChanged("schTimeFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime schTimeTo {
            get {
                return this.schTimeToField;
            }
            set {
                this.schTimeToField = value;
                this.RaisePropertyChanged("schTimeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeToSpecified {
            get {
                return this.schTimeToFieldSpecified;
            }
            set {
                this.schTimeToFieldSpecified = value;
                this.RaisePropertyChanged("schTimeToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal schCoef {
            get {
                return this.schCoefField;
            }
            set {
                this.schCoefField = value;
                this.RaisePropertyChanged("schCoef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schCoefSpecified {
            get {
                return this.schCoefFieldSpecified;
            }
            set {
                this.schCoefFieldSpecified = value;
                this.RaisePropertyChanged("schCoefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal showId {
            get {
                return this.showIdField;
            }
            set {
                this.showIdField = value;
                this.RaisePropertyChanged("showId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showIdSpecified {
            get {
                return this.showIdFieldSpecified;
            }
            set {
                this.showIdFieldSpecified = value;
                this.RaisePropertyChanged("showIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(seat))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scheduler))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tickets))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class seat : baseModel {
        
        private bool seatIsactiveField;
        
        private int seatColumnField;
        
        private int seatNumField;
        
        private int seatRowField;
        
        private int seatTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool seatIsactive {
            get {
                return this.seatIsactiveField;
            }
            set {
                this.seatIsactiveField = value;
                this.RaisePropertyChanged("seatIsactive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int seatColumn {
            get {
                return this.seatColumnField;
            }
            set {
                this.seatColumnField = value;
                this.RaisePropertyChanged("seatColumn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int seatNum {
            get {
                return this.seatNumField;
            }
            set {
                this.seatNumField = value;
                this.RaisePropertyChanged("seatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int seatRow {
            get {
                return this.seatRowField;
            }
            set {
                this.seatRowField = value;
                this.RaisePropertyChanged("seatRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int seatType {
            get {
                return this.seatTypeField;
            }
            set {
                this.seatTypeField = value;
                this.RaisePropertyChanged("seatType");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTickets", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getTicketsRequest {
        
        public getTicketsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicketsResponse", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.TicketService.tickets[] @return;
        
        public getTicketsResponse() {
        }
        
        public getTicketsResponse(EntertainmentNetwork.DAL.TicketService.tickets[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveTickets", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveTicketsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.TicketService.tickets[] arg0;
        
        public saveTicketsRequest() {
        }
        
        public saveTicketsRequest(EntertainmentNetwork.DAL.TicketService.tickets[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveTicketsResponse", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveTicketsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.TicketService.tickets[] @return;
        
        public saveTicketsResponse() {
        }
        
        public saveTicketsResponse(EntertainmentNetwork.DAL.TicketService.tickets[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicketsByScheduleID", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getTicketsByScheduleIDRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public getTicketsByScheduleIDRequest() {
        }
        
        public getTicketsByScheduleIDRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getTicketsByScheduleIDResponse", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getTicketsByScheduleIDResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.TicketService.tickets[] @return;
        
        public getTicketsByScheduleIDResponse() {
        }
        
        public getTicketsByScheduleIDResponse(EntertainmentNetwork.DAL.TicketService.tickets[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateTicket", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class generateTicketRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal schedulerID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal seatID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal sectionID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal showID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal orderID;
        
        public generateTicketRequest() {
        }
        
        public generateTicketRequest(decimal schedulerID, decimal seatID, decimal sectionID, decimal showID, decimal orderID) {
            this.schedulerID = schedulerID;
            this.seatID = seatID;
            this.sectionID = sectionID;
            this.showID = showID;
            this.orderID = orderID;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateTicketResponse", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class generateTicketResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.TicketService.tickets @return;
        
        public generateTicketResponse() {
        }
        
        public generateTicketResponse(EntertainmentNetwork.DAL.TicketService.tickets @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findTicketById", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findTicketByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findTicketByIdRequest() {
        }
        
        public findTicketByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findTicketByIdResponse", WrapperNamespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findTicketByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://TicketServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.TicketService.tickets[] @return;
        
        public findTicketByIdResponse() {
        }
        
        public findTicketByIdResponse(EntertainmentNetwork.DAL.TicketService.tickets[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface TicketServiceChannel : EntertainmentNetwork.DAL.TicketService.TicketService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class TicketServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.TicketService.TicketService>, EntertainmentNetwork.DAL.TicketService.TicketService {
        
        public TicketServiceClient() {
        }
        
        public TicketServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public TicketServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public TicketServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.TicketService.removeTicketResponse EntertainmentNetwork.DAL.TicketService.TicketService.removeTicket(EntertainmentNetwork.DAL.TicketService.removeTicketRequest request) {
            return base.Channel.removeTicket(request);
        }
        
        public void removeTicket(decimal arg0) {
            EntertainmentNetwork.DAL.TicketService.removeTicketRequest inValue = new EntertainmentNetwork.DAL.TicketService.removeTicketRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.TicketService.removeTicketResponse retVal = ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).removeTicket(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.removeTicketResponse> EntertainmentNetwork.DAL.TicketService.TicketService.removeTicketAsync(EntertainmentNetwork.DAL.TicketService.removeTicketRequest request) {
            return base.Channel.removeTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.removeTicketResponse> removeTicketAsync(decimal arg0) {
            EntertainmentNetwork.DAL.TicketService.removeTicketRequest inValue = new EntertainmentNetwork.DAL.TicketService.removeTicketRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).removeTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.TicketService.getTicketsResponse EntertainmentNetwork.DAL.TicketService.TicketService.getTickets(EntertainmentNetwork.DAL.TicketService.getTicketsRequest request) {
            return base.Channel.getTickets(request);
        }
        
        public EntertainmentNetwork.DAL.TicketService.tickets[] getTickets() {
            EntertainmentNetwork.DAL.TicketService.getTicketsRequest inValue = new EntertainmentNetwork.DAL.TicketService.getTicketsRequest();
            EntertainmentNetwork.DAL.TicketService.getTicketsResponse retVal = ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).getTickets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.getTicketsResponse> EntertainmentNetwork.DAL.TicketService.TicketService.getTicketsAsync(EntertainmentNetwork.DAL.TicketService.getTicketsRequest request) {
            return base.Channel.getTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.getTicketsResponse> getTicketsAsync() {
            EntertainmentNetwork.DAL.TicketService.getTicketsRequest inValue = new EntertainmentNetwork.DAL.TicketService.getTicketsRequest();
            return ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).getTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.TicketService.saveTicketsResponse EntertainmentNetwork.DAL.TicketService.TicketService.saveTickets(EntertainmentNetwork.DAL.TicketService.saveTicketsRequest request) {
            return base.Channel.saveTickets(request);
        }
        
        public EntertainmentNetwork.DAL.TicketService.tickets[] saveTickets(EntertainmentNetwork.DAL.TicketService.tickets[] arg0) {
            EntertainmentNetwork.DAL.TicketService.saveTicketsRequest inValue = new EntertainmentNetwork.DAL.TicketService.saveTicketsRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.TicketService.saveTicketsResponse retVal = ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).saveTickets(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.saveTicketsResponse> EntertainmentNetwork.DAL.TicketService.TicketService.saveTicketsAsync(EntertainmentNetwork.DAL.TicketService.saveTicketsRequest request) {
            return base.Channel.saveTicketsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.saveTicketsResponse> saveTicketsAsync(EntertainmentNetwork.DAL.TicketService.tickets[] arg0) {
            EntertainmentNetwork.DAL.TicketService.saveTicketsRequest inValue = new EntertainmentNetwork.DAL.TicketService.saveTicketsRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).saveTicketsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDResponse EntertainmentNetwork.DAL.TicketService.TicketService.getTicketsByScheduleID(EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest request) {
            return base.Channel.getTicketsByScheduleID(request);
        }
        
        public EntertainmentNetwork.DAL.TicketService.tickets[] getTicketsByScheduleID(decimal arg0) {
            EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest inValue = new EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDResponse retVal = ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).getTicketsByScheduleID(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDResponse> EntertainmentNetwork.DAL.TicketService.TicketService.getTicketsByScheduleIDAsync(EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest request) {
            return base.Channel.getTicketsByScheduleIDAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDResponse> getTicketsByScheduleIDAsync(decimal arg0) {
            EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest inValue = new EntertainmentNetwork.DAL.TicketService.getTicketsByScheduleIDRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).getTicketsByScheduleIDAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.TicketService.generateTicketResponse EntertainmentNetwork.DAL.TicketService.TicketService.generateTicket(EntertainmentNetwork.DAL.TicketService.generateTicketRequest request) {
            return base.Channel.generateTicket(request);
        }
        
        public EntertainmentNetwork.DAL.TicketService.tickets generateTicket(decimal schedulerID, decimal seatID, decimal sectionID, decimal showID, decimal orderID) {
            EntertainmentNetwork.DAL.TicketService.generateTicketRequest inValue = new EntertainmentNetwork.DAL.TicketService.generateTicketRequest();
            inValue.schedulerID = schedulerID;
            inValue.seatID = seatID;
            inValue.sectionID = sectionID;
            inValue.showID = showID;
            inValue.orderID = orderID;
            EntertainmentNetwork.DAL.TicketService.generateTicketResponse retVal = ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).generateTicket(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.generateTicketResponse> EntertainmentNetwork.DAL.TicketService.TicketService.generateTicketAsync(EntertainmentNetwork.DAL.TicketService.generateTicketRequest request) {
            return base.Channel.generateTicketAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.generateTicketResponse> generateTicketAsync(decimal schedulerID, decimal seatID, decimal sectionID, decimal showID, decimal orderID) {
            EntertainmentNetwork.DAL.TicketService.generateTicketRequest inValue = new EntertainmentNetwork.DAL.TicketService.generateTicketRequest();
            inValue.schedulerID = schedulerID;
            inValue.seatID = seatID;
            inValue.sectionID = sectionID;
            inValue.showID = showID;
            inValue.orderID = orderID;
            return ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).generateTicketAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.TicketService.findTicketByIdResponse EntertainmentNetwork.DAL.TicketService.TicketService.findTicketById(EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest request) {
            return base.Channel.findTicketById(request);
        }
        
        public EntertainmentNetwork.DAL.TicketService.tickets[] findTicketById(decimal arg0) {
            EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest inValue = new EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.TicketService.findTicketByIdResponse retVal = ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).findTicketById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.findTicketByIdResponse> EntertainmentNetwork.DAL.TicketService.TicketService.findTicketByIdAsync(EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest request) {
            return base.Channel.findTicketByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.TicketService.findTicketByIdResponse> findTicketByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest inValue = new EntertainmentNetwork.DAL.TicketService.findTicketByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.TicketService.TicketService)(this)).findTicketByIdAsync(inValue);
        }
    }
}
