//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.OrdersService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", ConfigurationName="OrdersService.OrderService")]
    public interface OrderService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/re" +
            "moveOrderRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/re" +
            "moveOrderResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EntertainmentNetwork.DAL.OrdersService.ServiceException), Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/re" +
            "moveOrder/Fault/ServiceException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetwork.DAL.OrdersService.removeOrderResponse removeOrder(EntertainmentNetwork.DAL.OrdersService.removeOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/re" +
            "moveOrderRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/re" +
            "moveOrderResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.removeOrderResponse> removeOrderAsync(EntertainmentNetwork.DAL.OrdersService.removeOrderRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "tOrdersRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "tOrdersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.OrdersService.getOrdersResponse getOrders(EntertainmentNetwork.DAL.OrdersService.getOrdersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "tOrdersRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "tOrdersResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.getOrdersResponse> getOrdersAsync(EntertainmentNetwork.DAL.OrdersService.getOrdersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "nerateOrderRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "nerateOrderResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.OrdersService.generateOrderResponse generateOrder(EntertainmentNetwork.DAL.OrdersService.generateOrderRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "nerateOrderRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/ge" +
            "nerateOrderResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.generateOrderResponse> generateOrderAsync(EntertainmentNetwork.DAL.OrdersService.generateOrderRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/fi" +
            "ndOrdersByIdRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/fi" +
            "ndOrdersByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.OrdersService.findOrdersByIdResponse findOrdersById(EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/fi" +
            "ndOrdersByIdRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/fi" +
            "ndOrdersByIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.findOrdersByIdResponse> findOrdersByIdAsync(EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/sa" +
            "veRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/sa" +
            "veResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.OrdersService.saveResponse save(EntertainmentNetwork.DAL.OrdersService.saveRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/sa" +
            "veRequest", ReplyAction="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/OrderService/sa" +
            "veResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.saveResponse> saveAsync(EntertainmentNetwork.DAL.OrdersService.saveRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeOrder", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeOrderRequest() {
        }
        
        public removeOrderRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeOrderResponse", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeOrderResponse {
        
        public removeOrderResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class orders : baseModel {
        
        private System.DateTime ordDateField;
        
        private bool ordDateFieldSpecified;
        
        private string ordCommField;
        
        private decimal ordCostField;
        
        private bool ordCostFieldSpecified;
        
        private tickets[] ticketsesField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public System.DateTime ordDate {
            get {
                return this.ordDateField;
            }
            set {
                this.ordDateField = value;
                this.RaisePropertyChanged("ordDate");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordDateSpecified {
            get {
                return this.ordDateFieldSpecified;
            }
            set {
                this.ordDateFieldSpecified = value;
                this.RaisePropertyChanged("ordDateSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string ordComm {
            get {
                return this.ordCommField;
            }
            set {
                this.ordCommField = value;
                this.RaisePropertyChanged("ordComm");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal ordCost {
            get {
                return this.ordCostField;
            }
            set {
                this.ordCostField = value;
                this.RaisePropertyChanged("ordCost");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordCostSpecified {
            get {
                return this.ordCostFieldSpecified;
            }
            set {
                this.ordCostFieldSpecified = value;
                this.RaisePropertyChanged("ordCostSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("ticketses", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public tickets[] ticketses {
            get {
                return this.ticketsesField;
            }
            set {
                this.ticketsesField = value;
                this.RaisePropertyChanged("ticketses");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class tickets : baseModel {
        
        private scheduler schedulerField;
        
        private seat seatField;
        
        private decimal tctPriceField;
        
        private bool tctPriceFieldSpecified;
        
        private bool tctIssoldField;
        
        private decimal ordersIdField;
        
        private bool ordersIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public scheduler scheduler {
            get {
                return this.schedulerField;
            }
            set {
                this.schedulerField = value;
                this.RaisePropertyChanged("scheduler");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public seat seat {
            get {
                return this.seatField;
            }
            set {
                this.seatField = value;
                this.RaisePropertyChanged("seat");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public decimal tctPrice {
            get {
                return this.tctPriceField;
            }
            set {
                this.tctPriceField = value;
                this.RaisePropertyChanged("tctPrice");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool tctPriceSpecified {
            get {
                return this.tctPriceFieldSpecified;
            }
            set {
                this.tctPriceFieldSpecified = value;
                this.RaisePropertyChanged("tctPriceSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public bool tctIssold {
            get {
                return this.tctIssoldField;
            }
            set {
                this.tctIssoldField = value;
                this.RaisePropertyChanged("tctIssold");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal ordersId {
            get {
                return this.ordersIdField;
            }
            set {
                this.ordersIdField = value;
                this.RaisePropertyChanged("ordersId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool ordersIdSpecified {
            get {
                return this.ordersIdFieldSpecified;
            }
            set {
                this.ordersIdFieldSpecified = value;
                this.RaisePropertyChanged("ordersIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class scheduler : baseModel {
        
        private string schDescrField;
        
        private System.DateTime schTimeFromField;
        
        private bool schTimeFromFieldSpecified;
        
        private System.DateTime schTimeToField;
        
        private bool schTimeToFieldSpecified;
        
        private decimal schCoefField;
        
        private bool schCoefFieldSpecified;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        private decimal showIdField;
        
        private bool showIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string schDescr {
            get {
                return this.schDescrField;
            }
            set {
                this.schDescrField = value;
                this.RaisePropertyChanged("schDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime schTimeFrom {
            get {
                return this.schTimeFromField;
            }
            set {
                this.schTimeFromField = value;
                this.RaisePropertyChanged("schTimeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeFromSpecified {
            get {
                return this.schTimeFromFieldSpecified;
            }
            set {
                this.schTimeFromFieldSpecified = value;
                this.RaisePropertyChanged("schTimeFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime schTimeTo {
            get {
                return this.schTimeToField;
            }
            set {
                this.schTimeToField = value;
                this.RaisePropertyChanged("schTimeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeToSpecified {
            get {
                return this.schTimeToFieldSpecified;
            }
            set {
                this.schTimeToFieldSpecified = value;
                this.RaisePropertyChanged("schTimeToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal schCoef {
            get {
                return this.schCoefField;
            }
            set {
                this.schCoefField = value;
                this.RaisePropertyChanged("schCoef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schCoefSpecified {
            get {
                return this.schCoefFieldSpecified;
            }
            set {
                this.schCoefFieldSpecified = value;
                this.RaisePropertyChanged("schCoefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal showId {
            get {
                return this.showIdField;
            }
            set {
                this.showIdField = value;
                this.RaisePropertyChanged("showId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showIdSpecified {
            get {
                return this.showIdFieldSpecified;
            }
            set {
                this.showIdFieldSpecified = value;
                this.RaisePropertyChanged("showIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(seat))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scheduler))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(tickets))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(orders))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class seat : baseModel {
        
        private bool seatIsactiveField;
        
        private int seatColumnField;
        
        private int seatNumField;
        
        private int seatRowField;
        
        private int seatTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool seatIsactive {
            get {
                return this.seatIsactiveField;
            }
            set {
                this.seatIsactiveField = value;
                this.RaisePropertyChanged("seatIsactive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int seatColumn {
            get {
                return this.seatColumnField;
            }
            set {
                this.seatColumnField = value;
                this.RaisePropertyChanged("seatColumn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int seatNum {
            get {
                return this.seatNumField;
            }
            set {
                this.seatNumField = value;
                this.RaisePropertyChanged("seatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int seatRow {
            get {
                return this.seatRowField;
            }
            set {
                this.seatRowField = value;
                this.RaisePropertyChanged("seatRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int seatType {
            get {
                return this.seatTypeField;
            }
            set {
                this.seatTypeField = value;
                this.RaisePropertyChanged("seatType");
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrders", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getOrdersRequest {
        
        public getOrdersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getOrdersResponse", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getOrdersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.OrdersService.orders[] @return;
        
        public getOrdersResponse() {
        }
        
        public getOrdersResponse(EntertainmentNetwork.DAL.OrdersService.orders[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateOrder", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class generateOrderRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public generateOrderRequest() {
        }
        
        public generateOrderRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateOrderResponse", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class generateOrderResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.OrdersService.orders @return;
        
        public generateOrderResponse() {
        }
        
        public generateOrderResponse(EntertainmentNetwork.DAL.OrdersService.orders @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOrdersById", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findOrdersByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findOrdersByIdRequest() {
        }
        
        public findOrdersByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findOrdersByIdResponse", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findOrdersByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.OrdersService.orders[] @return;
        
        public findOrdersByIdResponse() {
        }
        
        public findOrdersByIdResponse(EntertainmentNetwork.DAL.OrdersService.orders[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="save", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string arg0;
        
        public saveRequest() {
        }
        
        public saveRequest(string arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveResponse", WrapperNamespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://OrderService.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.OrdersService.orders @return;
        
        public saveResponse() {
        }
        
        public saveResponse(EntertainmentNetwork.DAL.OrdersService.orders @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface OrderServiceChannel : EntertainmentNetwork.DAL.OrdersService.OrderService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class OrderServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.OrdersService.OrderService>, EntertainmentNetwork.DAL.OrdersService.OrderService {
        
        public OrderServiceClient() {
        }
        
        public OrderServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public OrderServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.OrdersService.removeOrderResponse EntertainmentNetwork.DAL.OrdersService.OrderService.removeOrder(EntertainmentNetwork.DAL.OrdersService.removeOrderRequest request) {
            return base.Channel.removeOrder(request);
        }
        
        public void removeOrder(decimal arg0) {
            EntertainmentNetwork.DAL.OrdersService.removeOrderRequest inValue = new EntertainmentNetwork.DAL.OrdersService.removeOrderRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.OrdersService.removeOrderResponse retVal = ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).removeOrder(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.removeOrderResponse> EntertainmentNetwork.DAL.OrdersService.OrderService.removeOrderAsync(EntertainmentNetwork.DAL.OrdersService.removeOrderRequest request) {
            return base.Channel.removeOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.removeOrderResponse> removeOrderAsync(decimal arg0) {
            EntertainmentNetwork.DAL.OrdersService.removeOrderRequest inValue = new EntertainmentNetwork.DAL.OrdersService.removeOrderRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).removeOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.OrdersService.getOrdersResponse EntertainmentNetwork.DAL.OrdersService.OrderService.getOrders(EntertainmentNetwork.DAL.OrdersService.getOrdersRequest request) {
            return base.Channel.getOrders(request);
        }
        
        public EntertainmentNetwork.DAL.OrdersService.orders[] getOrders() {
            EntertainmentNetwork.DAL.OrdersService.getOrdersRequest inValue = new EntertainmentNetwork.DAL.OrdersService.getOrdersRequest();
            EntertainmentNetwork.DAL.OrdersService.getOrdersResponse retVal = ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).getOrders(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.getOrdersResponse> EntertainmentNetwork.DAL.OrdersService.OrderService.getOrdersAsync(EntertainmentNetwork.DAL.OrdersService.getOrdersRequest request) {
            return base.Channel.getOrdersAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.getOrdersResponse> getOrdersAsync() {
            EntertainmentNetwork.DAL.OrdersService.getOrdersRequest inValue = new EntertainmentNetwork.DAL.OrdersService.getOrdersRequest();
            return ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).getOrdersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.OrdersService.generateOrderResponse EntertainmentNetwork.DAL.OrdersService.OrderService.generateOrder(EntertainmentNetwork.DAL.OrdersService.generateOrderRequest request) {
            return base.Channel.generateOrder(request);
        }
        
        public EntertainmentNetwork.DAL.OrdersService.orders generateOrder(string arg0) {
            EntertainmentNetwork.DAL.OrdersService.generateOrderRequest inValue = new EntertainmentNetwork.DAL.OrdersService.generateOrderRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.OrdersService.generateOrderResponse retVal = ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).generateOrder(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.generateOrderResponse> EntertainmentNetwork.DAL.OrdersService.OrderService.generateOrderAsync(EntertainmentNetwork.DAL.OrdersService.generateOrderRequest request) {
            return base.Channel.generateOrderAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.generateOrderResponse> generateOrderAsync(string arg0) {
            EntertainmentNetwork.DAL.OrdersService.generateOrderRequest inValue = new EntertainmentNetwork.DAL.OrdersService.generateOrderRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).generateOrderAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.OrdersService.findOrdersByIdResponse EntertainmentNetwork.DAL.OrdersService.OrderService.findOrdersById(EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest request) {
            return base.Channel.findOrdersById(request);
        }
        
        public EntertainmentNetwork.DAL.OrdersService.orders[] findOrdersById(decimal arg0) {
            EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest inValue = new EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.OrdersService.findOrdersByIdResponse retVal = ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).findOrdersById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.findOrdersByIdResponse> EntertainmentNetwork.DAL.OrdersService.OrderService.findOrdersByIdAsync(EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest request) {
            return base.Channel.findOrdersByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.findOrdersByIdResponse> findOrdersByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest inValue = new EntertainmentNetwork.DAL.OrdersService.findOrdersByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).findOrdersByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.OrdersService.saveResponse EntertainmentNetwork.DAL.OrdersService.OrderService.save(EntertainmentNetwork.DAL.OrdersService.saveRequest request) {
            return base.Channel.save(request);
        }
        
        public EntertainmentNetwork.DAL.OrdersService.orders save(string arg0) {
            EntertainmentNetwork.DAL.OrdersService.saveRequest inValue = new EntertainmentNetwork.DAL.OrdersService.saveRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.OrdersService.saveResponse retVal = ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).save(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.saveResponse> EntertainmentNetwork.DAL.OrdersService.OrderService.saveAsync(EntertainmentNetwork.DAL.OrdersService.saveRequest request) {
            return base.Channel.saveAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.OrdersService.saveResponse> saveAsync(string arg0) {
            EntertainmentNetwork.DAL.OrdersService.saveRequest inValue = new EntertainmentNetwork.DAL.OrdersService.saveRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.OrdersService.OrderService)(this)).saveAsync(inValue);
        }
    }
}
