
--------------------------------------------------------
--  DDL for Sequences
--------------------------------------------------------
   CREATE SEQUENCE  "TEST"."CINEMA_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."CITY_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 41 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."HALL_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."SEC_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."SEAT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."SHW_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."ORD_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."SCH_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   CREATE SEQUENCE  "TEST"."TCT_SEQ"  MINVALUE 1 MAXVALUE 9999999999999999999999999999 INCREMENT BY 1 START WITH 21 CACHE 20 NOORDER  NOCYCLE ;
   
--------------------------------------------------------
--  DDL for Table CITY
--------------------------------------------------------

  CREATE TABLE "TEST"."CITY" 
   (	"CIT_ID" NUMBER NOT NULL,
	"CIT_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"CIT_COUNTRY" VARCHAR2(100 BYTE) NOT NULL,
	CONSTRAINT "CITY_PK" PRIMARY KEY ("CIT_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
  --------------------------------------------------------
--  DDL for Table CINEMA
--------------------------------------------------------

  CREATE TABLE "TEST"."CINEMA" 
   (	"CIN_ID" NUMBER NOT NULL, 
	"CIN_NAME" VARCHAR2(100 BYTE) NOT NULL,
	"CIN_ICON" BLOB, 
	"CIN_ADDRESS" VARCHAR2(255 BYTE) NOT NULL,
	"CIN_CITY_ID" NUMBER NOT NULL,
	CONSTRAINT "CINEMA_PK" PRIMARY KEY ("CIN_ID"),
	CONSTRAINT "CINEMA_FK" FOREIGN KEY ("CIN_CITY_ID") REFERENCES "TEST"."CITY" ("CIT_ID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
 LOB ("CIN_ICON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  
--------------------------------------------------------
--  DDL for Table HALL
--------------------------------------------------------

  CREATE TABLE "TEST"."HALL" 
   (	"HAL_ID" NUMBER NOT NULL,
	"HAL_CIN_ID" NUMBER NOT NULL,
	"HAL_NAME" VARCHAR2(100 BYTE) NOT NULL,
	CONSTRAINT "HALL_PK" PRIMARY KEY ("HAL_ID"),
	CONSTRAINT "HALL_FK" FOREIGN KEY ("HAL_CIN_ID") REFERENCES "TEST"."CINEMA" ("CIN_ID") ON DELETE CASCADE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Table SECTION
--------------------------------------------------------
  
  CREATE TABLE "TEST"."SECTION" 
   (	"SEC_HAL_ID" NUMBER NOT NULL,
	"SEC_ID" NUMBER NOT NULL,
	"SEC_NAME" VARCHAR2(100 BYTE),
	"SEC_COEF" NUMBER DEFAULT 1 NOT NULL,
	CONSTRAINT "SEC_PK" PRIMARY KEY ("SEC_ID"),
	CONSTRAINT "SEC_FK" FOREIGN KEY ("SEC_HAL_ID") REFERENCES "TEST"."HALL" ("HAL_ID") ON DELETE CASCADE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Table SEAT
--------------------------------------------------------

 CREATE TABLE "TEST"."SEAT" 
   (	"SEAT_ID" NUMBER NOT NULL,
	"SEAT_SEC_ID" NUMBER NOT NULL,
	"SEAT_COLUMN" NUMBER NOT NULL,
	"SEAT_NUM" NUMBER NOT NULL,
	"SEAT_ROW" NUMBER NOT NULL,
	"SEAT_TYPE" NUMBER DEFAULT 0 NOT NULL,
	"SEAT_ISACTIVE" NUMBER(1,0) DEFAULT 1 NOT NULL,
	CONSTRAINT "SEAT_PK" PRIMARY KEY ("SEAT_ID"),
	CONSTRAINT "SEAT_FK" FOREIGN KEY ("SEAT_SEC_ID") REFERENCES "TEST"."SECTION" ("SEC_ID") ON DELETE CASCADE
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Table SHOW
-------------------------------------------------------- 
CREATE TABLE "TEST"."SHOW" 
   (	"SHW_ID" NUMBER NOT NULL,
	"SHW_NAME" VARCHAR2(100 BYTE) NOT NULL, 
	"SHW_DESCR" VARCHAR2(255 BYTE),
  "SHW_PERFORMER" VARCHAR2(100 BYTE),
  "SHW_ICON" BLOB,
  "SHW_PRICE" NUMBER DEFAULT 0 NOT NULL,
  "SHW_STARTDT" DATE,
  "SHW_ENDDT" DATE,
	CONSTRAINT "SHOW_PK" PRIMARY KEY ("SHW_ID")
   ) SEGMENT CREATION DEFERRED 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  TABLESPACE "USERS" 
  LOB ("SHW_ICON") STORE AS SECUREFILE (
  TABLESPACE "USERS" ENABLE STORAGE IN ROW CHUNK 8192
  NOCACHE LOGGING  NOCOMPRESS  KEEP_DUPLICATES ) ;
  
--------------------------------------------------------
--  DDL for Table ORDERS
--------------------------------------------------------
 
  CREATE TABLE "TEST"."ORDERS" 
   (	"ORD_ID" NUMBER NOT NULL,
	"ORD_DATE" DATE DEFAULT SYSDATE  NOT NULL, 
	"ORD_COMM" VARCHAR2(255 BYTE),
  "ORD_COST" NUMBER,
	CONSTRAINT "ORD_PK" PRIMARY KEY ("ORD_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;
  
--------------------------------------------------------
--  DDL for Table SCHEDULER
-------------------------------------------------------- 
  
CREATE TABLE "TEST"."SCHEDULER" 
   (	"SCH_ID" NUMBER NOT NULL,
  "SCH_HAL_ID" NUMBER NOT NULL,
  "SCH_SHW_ID" NUMBER NOT NULL,
  "SCH_NAME" VARCHAR2(100 BYTE) NOT NULL, 
  "SCH_DESCR" VARCHAR2(255 BYTE),
  "SCH_TIME_FROM" DATE,
  "SCH_TIME_TO" DATE,
  "SCH_COEF" NUMBER DEFAULT 1 NOT NULL,
  CONSTRAINT "SCH_PK" PRIMARY KEY ("SCH_ID"),
  CONSTRAINT "SCH_FK_HAL" FOREIGN KEY ("SCH_HAL_ID") REFERENCES "TEST"."HALL" ("HAL_ID"),
  CONSTRAINT "SCH_FK_SHW" FOREIGN KEY ("SCH_SHW_ID") REFERENCES "TEST"."SHOW" ("SHW_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

--------------------------------------------------------
--  DDL for Table TICKETS
--------------------------------------------------------  

  CREATE TABLE "TEST"."TICKETS" 
   (	"TCT_ID" NUMBER NOT NULL,
  "TCT_SEAT_ID" NUMBER NOT NULL,
  "TCT_ORD_ID" NUMBER NOT NULL,
  "TCT_SCH_ID" NUMBER NOT NULL,
  "TCT_PRICE" NUMBER NOT NULL, 
  "TCT_ISSOLD" NUMBER(1,0) DEFAULT 0 NOT NULL,
  CONSTRAINT "TCT_PK" PRIMARY KEY ("TCT_ID"),
  CONSTRAINT "TCT_FK_SEAT" FOREIGN KEY ("TCT_SEAT_ID") REFERENCES "TEST"."SEAT" ("SEAT_ID"),
  CONSTRAINT "TCT_FK_ORD" FOREIGN KEY ("TCT_ORD_ID") REFERENCES "TEST"."ORDERS" ("ORD_ID"),
  CONSTRAINT "TCT_FK_SCH" FOREIGN KEY ("TCT_SCH_ID") REFERENCES "TEST"."SCHEDULER" ("SCH_ID"),
  CONSTRAINT "TCT_UNIQ" UNIQUE ("TCT_SEAT_ID", "TCT_SCH_ID")
   ) SEGMENT CREATION IMMEDIATE 
  PCTFREE 10 PCTUSED 40 INITRANS 1 MAXTRANS 255 NOCOMPRESS LOGGING
  STORAGE(INITIAL 65536 NEXT 1048576 MINEXTENTS 1 MAXEXTENTS 2147483645
  PCTINCREASE 0 FREELISTS 1 FREELIST GROUPS 1 BUFFER_POOL DEFAULT FLASH_CACHE DEFAULT CELL_FLASH_CACHE DEFAULT)
  TABLESPACE "USERS" ;

