//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.SchedulerService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", ConfigurationName="SchedulerService.SchedulerService")]
    public interface SchedulerService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/removeSchedulerRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/removeSchedulerResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EntertainmentNetwork.DAL.SchedulerService.ServiceException), Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/removeScheduler/Fault/ServiceException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse removeScheduler(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/removeSchedulerRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/removeSchedulerResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse> removeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse getSchedulers(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse> getSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/saveSchedulersRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/saveSchedulersResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.saveSchedulersResponse saveSchedulers(EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/saveSchedulersRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/saveSchedulersResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.saveSchedulersResponse> saveSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersByCinemaHallShowDatesRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersByCinemaHallShowDatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesResponse getSchedulersByCinemaHallShowDates(EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersByCinemaHallShowDatesRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/getSchedulersByCinemaHallShowDatesResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesResponse> getSchedulersByCinemaHallShowDatesAsync(EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/findSchedulerByIdRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/findSchedulerByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse findSchedulerById(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/findSchedulerByIdRequest", ReplyAction="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/SchedulerS" +
            "ervice/findSchedulerByIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse> findSchedulerByIdAsync(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeScheduler", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeSchedulerRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeSchedulerRequest() {
        }
        
        public removeSchedulerRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeSchedulerResponse", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeSchedulerResponse {
        
        public removeSchedulerResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class scheduler : baseModel {
        
        private string schDescrField;
        
        private System.DateTime schTimeFromField;
        
        private bool schTimeFromFieldSpecified;
        
        private System.DateTime schTimeToField;
        
        private bool schTimeToFieldSpecified;
        
        private decimal schCoefField;
        
        private bool schCoefFieldSpecified;
        
        private decimal hallIdField;
        
        private bool hallIdFieldSpecified;
        
        private decimal showIdField;
        
        private bool showIdFieldSpecified;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string schDescr {
            get {
                return this.schDescrField;
            }
            set {
                this.schDescrField = value;
                this.RaisePropertyChanged("schDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public System.DateTime schTimeFrom {
            get {
                return this.schTimeFromField;
            }
            set {
                this.schTimeFromField = value;
                this.RaisePropertyChanged("schTimeFrom");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeFromSpecified {
            get {
                return this.schTimeFromFieldSpecified;
            }
            set {
                this.schTimeFromFieldSpecified = value;
                this.RaisePropertyChanged("schTimeFromSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public System.DateTime schTimeTo {
            get {
                return this.schTimeToField;
            }
            set {
                this.schTimeToField = value;
                this.RaisePropertyChanged("schTimeTo");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schTimeToSpecified {
            get {
                return this.schTimeToFieldSpecified;
            }
            set {
                this.schTimeToFieldSpecified = value;
                this.RaisePropertyChanged("schTimeToSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public decimal schCoef {
            get {
                return this.schCoefField;
            }
            set {
                this.schCoefField = value;
                this.RaisePropertyChanged("schCoef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool schCoefSpecified {
            get {
                return this.schCoefFieldSpecified;
            }
            set {
                this.schCoefFieldSpecified = value;
                this.RaisePropertyChanged("schCoefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public decimal hallId {
            get {
                return this.hallIdField;
            }
            set {
                this.hallIdField = value;
                this.RaisePropertyChanged("hallId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool hallIdSpecified {
            get {
                return this.hallIdFieldSpecified;
            }
            set {
                this.hallIdFieldSpecified = value;
                this.RaisePropertyChanged("hallIdSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public decimal showId {
            get {
                return this.showIdField;
            }
            set {
                this.showIdField = value;
                this.RaisePropertyChanged("showId");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool showIdSpecified {
            get {
                return this.showIdFieldSpecified;
            }
            set {
                this.showIdFieldSpecified = value;
                this.RaisePropertyChanged("showIdSpecified");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(scheduler))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulers", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSchedulersRequest {
        
        public getSchedulersRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulersResponse", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSchedulersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return;
        
        public getSchedulersResponse() {
        }
        
        public getSchedulersResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveSchedulers", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveSchedulersRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] arg0;
        
        public saveSchedulersRequest() {
        }
        
        public saveSchedulersRequest(EntertainmentNetwork.DAL.SchedulerService.scheduler[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveSchedulersResponse", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveSchedulersResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return;
        
        public saveSchedulersResponse() {
        }
        
        public saveSchedulersResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulersByCinemaHallShowDates", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSchedulersByCinemaHallShowDatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> cinemaID;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> hallId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> showId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=3)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime startDt;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=4)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime endDt;
        
        public getSchedulersByCinemaHallShowDatesRequest() {
        }
        
        public getSchedulersByCinemaHallShowDatesRequest(System.Nullable<decimal> cinemaID, System.Nullable<decimal> hallId, System.Nullable<decimal> showId, System.DateTime startDt, System.DateTime endDt) {
            this.cinemaID = cinemaID;
            this.hallId = hallId;
            this.showId = showId;
            this.startDt = startDt;
            this.endDt = endDt;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSchedulersByCinemaHallShowDatesResponse", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSchedulersByCinemaHallShowDatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return;
        
        public getSchedulersByCinemaHallShowDatesResponse() {
        }
        
        public getSchedulersByCinemaHallShowDatesResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findSchedulerById", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findSchedulerByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findSchedulerByIdRequest() {
        }
        
        public findSchedulerByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findSchedulerByIdResponse", WrapperNamespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findSchedulerByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://SchedulerServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return;
        
        public findSchedulerByIdResponse() {
        }
        
        public findSchedulerByIdResponse(EntertainmentNetwork.DAL.SchedulerService.scheduler[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface SchedulerServiceChannel : EntertainmentNetwork.DAL.SchedulerService.SchedulerService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class SchedulerServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.SchedulerService.SchedulerService>, EntertainmentNetwork.DAL.SchedulerService.SchedulerService {
        
        public SchedulerServiceClient() {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public SchedulerServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse EntertainmentNetwork.DAL.SchedulerService.SchedulerService.removeScheduler(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request) {
            return base.Channel.removeScheduler(request);
        }
        
        public void removeScheduler(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).removeScheduler(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse> EntertainmentNetwork.DAL.SchedulerService.SchedulerService.removeSchedulerAsync(EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest request) {
            return base.Channel.removeSchedulerAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.removeSchedulerResponse> removeSchedulerAsync(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.removeSchedulerRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).removeSchedulerAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse EntertainmentNetwork.DAL.SchedulerService.SchedulerService.getSchedulers(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request) {
            return base.Channel.getSchedulers(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] getSchedulers() {
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest();
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).getSchedulers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse> EntertainmentNetwork.DAL.SchedulerService.SchedulerService.getSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest request) {
            return base.Channel.getSchedulersAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersResponse> getSchedulersAsync() {
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.getSchedulersRequest();
            return ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).getSchedulersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.saveSchedulersResponse EntertainmentNetwork.DAL.SchedulerService.SchedulerService.saveSchedulers(EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest request) {
            return base.Channel.saveSchedulers(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] saveSchedulers(EntertainmentNetwork.DAL.SchedulerService.scheduler[] arg0) {
            EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.saveSchedulersResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).saveSchedulers(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.saveSchedulersResponse> EntertainmentNetwork.DAL.SchedulerService.SchedulerService.saveSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest request) {
            return base.Channel.saveSchedulersAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.saveSchedulersResponse> saveSchedulersAsync(EntertainmentNetwork.DAL.SchedulerService.scheduler[] arg0) {
            EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.saveSchedulersRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).saveSchedulersAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesResponse EntertainmentNetwork.DAL.SchedulerService.SchedulerService.getSchedulersByCinemaHallShowDates(EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest request) {
            return base.Channel.getSchedulersByCinemaHallShowDates(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] getSchedulersByCinemaHallShowDates(System.Nullable<decimal> cinemaID, System.Nullable<decimal> hallId, System.Nullable<decimal> showId, System.DateTime startDt, System.DateTime endDt) {
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest();
            inValue.cinemaID = cinemaID;
            inValue.hallId = hallId;
            inValue.showId = showId;
            inValue.startDt = startDt;
            inValue.endDt = endDt;
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).getSchedulersByCinemaHallShowDates(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesResponse> EntertainmentNetwork.DAL.SchedulerService.SchedulerService.getSchedulersByCinemaHallShowDatesAsync(EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest request) {
            return base.Channel.getSchedulersByCinemaHallShowDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesResponse> getSchedulersByCinemaHallShowDatesAsync(System.Nullable<decimal> cinemaID, System.Nullable<decimal> hallId, System.Nullable<decimal> showId, System.DateTime startDt, System.DateTime endDt) {
            EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.getSchedulersByCinemaHallShowDatesRequest();
            inValue.cinemaID = cinemaID;
            inValue.hallId = hallId;
            inValue.showId = showId;
            inValue.startDt = startDt;
            inValue.endDt = endDt;
            return ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).getSchedulersByCinemaHallShowDatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse EntertainmentNetwork.DAL.SchedulerService.SchedulerService.findSchedulerById(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request) {
            return base.Channel.findSchedulerById(request);
        }
        
        public EntertainmentNetwork.DAL.SchedulerService.scheduler[] findSchedulerById(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse retVal = ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).findSchedulerById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse> EntertainmentNetwork.DAL.SchedulerService.SchedulerService.findSchedulerByIdAsync(EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest request) {
            return base.Channel.findSchedulerByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdResponse> findSchedulerByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest inValue = new EntertainmentNetwork.DAL.SchedulerService.findSchedulerByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.SchedulerService.SchedulerService)(this)).findSchedulerByIdAsync(inValue);
        }
    }
}
