//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.ShowService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", ConfigurationName="ShowService.ShowService")]
    public interface ShowService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/rem" +
            "oveShowRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/rem" +
            "oveShowResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EntertainmentNetwork.DAL.ShowService.ServiceException), Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/rem" +
            "oveShow/Fault/ServiceException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetwork.DAL.ShowService.removeShowResponse removeShow(EntertainmentNetwork.DAL.ShowService.removeShowRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/rem" +
            "oveShowRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/rem" +
            "oveShowResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.removeShowResponse> removeShowAsync(EntertainmentNetwork.DAL.ShowService.removeShowRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "ShowsRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "ShowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.getShowsResponse getShows(EntertainmentNetwork.DAL.ShowService.getShowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "ShowsRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "ShowsResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getShowsResponse> getShowsAsync(EntertainmentNetwork.DAL.ShowService.getShowsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/sav" +
            "eShowsRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/sav" +
            "eShowsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.saveShowsResponse saveShows(EntertainmentNetwork.DAL.ShowService.saveShowsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/sav" +
            "eShowsRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/sav" +
            "eShowsResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.saveShowsResponse> saveShowsAsync(EntertainmentNetwork.DAL.ShowService.saveShowsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "SimplifiedShowsByDatesRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "SimplifiedShowsByDatesResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesResponse getSimplifiedShowsByDates(EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "SimplifiedShowsByDatesRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/get" +
            "SimplifiedShowsByDatesResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesResponse> getSimplifiedShowsByDatesAsync(EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/fin" +
            "dShowByIdRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/fin" +
            "dShowByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.ShowService.findShowByIdResponse findShowById(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/fin" +
            "dShowByIdRequest", ReplyAction="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/ShowService/fin" +
            "dShowByIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.findShowByIdResponse> findShowByIdAsync(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeShow", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeShowRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeShowRequest() {
        }
        
        public removeShowRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeShowResponse", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeShowResponse {
        
        public removeShowResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class show : baseModel {
        
        private string shwPerformerField;
        
        private string shwDescrField;
        
        private byte[] shwIconField;
        
        private System.DateTime shwStartDtField;
        
        private bool shwStartDtFieldSpecified;
        
        private System.DateTime shwEndDtField;
        
        private bool shwEndDtFieldSpecified;
        
        private float shwPriceField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string shwPerformer {
            get {
                return this.shwPerformerField;
            }
            set {
                this.shwPerformerField = value;
                this.RaisePropertyChanged("shwPerformer");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string shwDescr {
            get {
                return this.shwDescrField;
            }
            set {
                this.shwDescrField = value;
                this.RaisePropertyChanged("shwDescr");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=2)]
        public byte[] shwIcon {
            get {
                return this.shwIconField;
            }
            set {
                this.shwIconField = value;
                this.RaisePropertyChanged("shwIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public System.DateTime shwStartDt {
            get {
                return this.shwStartDtField;
            }
            set {
                this.shwStartDtField = value;
                this.RaisePropertyChanged("shwStartDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shwStartDtSpecified {
            get {
                return this.shwStartDtFieldSpecified;
            }
            set {
                this.shwStartDtFieldSpecified = value;
                this.RaisePropertyChanged("shwStartDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public System.DateTime shwEndDt {
            get {
                return this.shwEndDtField;
            }
            set {
                this.shwEndDtField = value;
                this.RaisePropertyChanged("shwEndDt");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool shwEndDtSpecified {
            get {
                return this.shwEndDtFieldSpecified;
            }
            set {
                this.shwEndDtFieldSpecified = value;
                this.RaisePropertyChanged("shwEndDtSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=5)]
        public float shwPrice {
            get {
                return this.shwPriceField;
            }
            set {
                this.shwPriceField = value;
                this.RaisePropertyChanged("shwPrice");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(show))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getShows", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getShowsRequest {
        
        public getShowsRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getShowsResponse", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getShowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show[] @return;
        
        public getShowsResponse() {
        }
        
        public getShowsResponse(EntertainmentNetwork.DAL.ShowService.show[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveShows", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveShowsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show[] arg0;
        
        public saveShowsRequest() {
        }
        
        public saveShowsRequest(EntertainmentNetwork.DAL.ShowService.show[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveShowsResponse", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveShowsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show[] @return;
        
        public saveShowsResponse() {
        }
        
        public saveShowsResponse(EntertainmentNetwork.DAL.ShowService.show[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class immutablePair : pair {
        
        private object leftField;
        
        private object rightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object right {
            get {
                return this.rightField;
            }
            set {
                this.rightField = value;
                this.RaisePropertyChanged("right");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(immutablePair))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public abstract partial class pair : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSimplifiedShowsByDates", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSimplifiedShowsByDatesRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public System.DateTime arg1;
        
        public getSimplifiedShowsByDatesRequest() {
        }
        
        public getSimplifiedShowsByDatesRequest(System.DateTime arg0, System.DateTime arg1) {
            this.arg0 = arg0;
            this.arg1 = arg1;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSimplifiedShowsByDatesResponse", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSimplifiedShowsByDatesResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.immutablePair[] @return;
        
        public getSimplifiedShowsByDatesResponse() {
        }
        
        public getSimplifiedShowsByDatesResponse(EntertainmentNetwork.DAL.ShowService.immutablePair[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findShowById", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findShowByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findShowByIdRequest() {
        }
        
        public findShowByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findShowByIdResponse", WrapperNamespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findShowByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://ShowServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.ShowService.show[] @return;
        
        public findShowByIdResponse() {
        }
        
        public findShowByIdResponse(EntertainmentNetwork.DAL.ShowService.show[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface ShowServiceChannel : EntertainmentNetwork.DAL.ShowService.ShowService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class ShowServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.ShowService.ShowService>, EntertainmentNetwork.DAL.ShowService.ShowService {
        
        public ShowServiceClient() {
        }
        
        public ShowServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public ShowServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public ShowServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.removeShowResponse EntertainmentNetwork.DAL.ShowService.ShowService.removeShow(EntertainmentNetwork.DAL.ShowService.removeShowRequest request) {
            return base.Channel.removeShow(request);
        }
        
        public void removeShow(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.removeShowRequest inValue = new EntertainmentNetwork.DAL.ShowService.removeShowRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.removeShowResponse retVal = ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).removeShow(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.removeShowResponse> EntertainmentNetwork.DAL.ShowService.ShowService.removeShowAsync(EntertainmentNetwork.DAL.ShowService.removeShowRequest request) {
            return base.Channel.removeShowAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.removeShowResponse> removeShowAsync(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.removeShowRequest inValue = new EntertainmentNetwork.DAL.ShowService.removeShowRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).removeShowAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.getShowsResponse EntertainmentNetwork.DAL.ShowService.ShowService.getShows(EntertainmentNetwork.DAL.ShowService.getShowsRequest request) {
            return base.Channel.getShows(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.show[] getShows() {
            EntertainmentNetwork.DAL.ShowService.getShowsRequest inValue = new EntertainmentNetwork.DAL.ShowService.getShowsRequest();
            EntertainmentNetwork.DAL.ShowService.getShowsResponse retVal = ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).getShows(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getShowsResponse> EntertainmentNetwork.DAL.ShowService.ShowService.getShowsAsync(EntertainmentNetwork.DAL.ShowService.getShowsRequest request) {
            return base.Channel.getShowsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getShowsResponse> getShowsAsync() {
            EntertainmentNetwork.DAL.ShowService.getShowsRequest inValue = new EntertainmentNetwork.DAL.ShowService.getShowsRequest();
            return ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).getShowsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.saveShowsResponse EntertainmentNetwork.DAL.ShowService.ShowService.saveShows(EntertainmentNetwork.DAL.ShowService.saveShowsRequest request) {
            return base.Channel.saveShows(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.show[] saveShows(EntertainmentNetwork.DAL.ShowService.show[] arg0) {
            EntertainmentNetwork.DAL.ShowService.saveShowsRequest inValue = new EntertainmentNetwork.DAL.ShowService.saveShowsRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.saveShowsResponse retVal = ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).saveShows(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.saveShowsResponse> EntertainmentNetwork.DAL.ShowService.ShowService.saveShowsAsync(EntertainmentNetwork.DAL.ShowService.saveShowsRequest request) {
            return base.Channel.saveShowsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.saveShowsResponse> saveShowsAsync(EntertainmentNetwork.DAL.ShowService.show[] arg0) {
            EntertainmentNetwork.DAL.ShowService.saveShowsRequest inValue = new EntertainmentNetwork.DAL.ShowService.saveShowsRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).saveShowsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesResponse EntertainmentNetwork.DAL.ShowService.ShowService.getSimplifiedShowsByDates(EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest request) {
            return base.Channel.getSimplifiedShowsByDates(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.immutablePair[] getSimplifiedShowsByDates(System.DateTime arg0, System.DateTime arg1) {
            EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest inValue = new EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesResponse retVal = ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).getSimplifiedShowsByDates(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesResponse> EntertainmentNetwork.DAL.ShowService.ShowService.getSimplifiedShowsByDatesAsync(EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest request) {
            return base.Channel.getSimplifiedShowsByDatesAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesResponse> getSimplifiedShowsByDatesAsync(System.DateTime arg0, System.DateTime arg1) {
            EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest inValue = new EntertainmentNetwork.DAL.ShowService.getSimplifiedShowsByDatesRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            return ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).getSimplifiedShowsByDatesAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.ShowService.findShowByIdResponse EntertainmentNetwork.DAL.ShowService.ShowService.findShowById(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request) {
            return base.Channel.findShowById(request);
        }
        
        public EntertainmentNetwork.DAL.ShowService.show[] findShowById(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.findShowByIdRequest inValue = new EntertainmentNetwork.DAL.ShowService.findShowByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.ShowService.findShowByIdResponse retVal = ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).findShowById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.findShowByIdResponse> EntertainmentNetwork.DAL.ShowService.ShowService.findShowByIdAsync(EntertainmentNetwork.DAL.ShowService.findShowByIdRequest request) {
            return base.Channel.findShowByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.ShowService.findShowByIdResponse> findShowByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.ShowService.findShowByIdRequest inValue = new EntertainmentNetwork.DAL.ShowService.findShowByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.ShowService.ShowService)(this)).findShowByIdAsync(inValue);
        }
    }
}
