//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace EntertainmentNetwork.DAL.CinemaService {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class ServiceException : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", ConfigurationName="CinemaService.CinemaService")]
    public interface CinemaService {
        
        // CODEGEN: Parameter 'arg0' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/removeCinemaRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/removeCinemaResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(EntertainmentNetwork.DAL.CinemaService.ServiceException), Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/removeCinema/Fault/ServiceException", Name="ServiceException")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse removeCinema(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/removeCinemaRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/removeCinemaResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse> removeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getCinemasRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getCinemasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.getCinemasResponse getCinemas(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getCinemasRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getCinemasResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getCinemasResponse> getCinemasAsync(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/saveCinemasRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/saveCinemasResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.saveCinemasResponse saveCinemas(EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/saveCinemasRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/saveCinemasResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.saveCinemasResponse> saveCinemasAsync(EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/findCinemaByIdRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/findCinemaByIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse findCinemaById(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/findCinemaByIdRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/findCinemaByIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse> findCinemaByIdAsync(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/generateSeatsRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/generateSeatsResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.generateSeatsResponse generateSeats(EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/generateSeatsRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/generateSeatsResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.generateSeatsResponse> generateSeatsAsync(EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest request);
        
        // CODEGEN: Parameter 'return' requires additional schema information that cannot be captured using the parameter mode. The specific attribute is 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getSimplifiedCinemasByCityIdShowIdRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getSimplifiedCinemasByCityIdShowIdResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdResponse getSimplifiedCinemasByCityIdShowId(EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getSimplifiedCinemasByCityIdShowIdRequest", ReplyAction="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/CinemaService" +
            "/getSimplifiedCinemasByCityIdShowIdResponse")]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdResponse> getSimplifiedCinemasByCityIdShowIdAsync(EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCinema", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeCinemaRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public removeCinemaRequest() {
        }
        
        public removeCinemaRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="removeCinemaResponse", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class removeCinemaResponse {
        
        public removeCinemaResponse() {
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class cinema : baseModel {
        
        private string cityField;
        
        private byte[] cinIconField;
        
        private string cinAddressField;
        
        private hall[] hallsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string city {
            get {
                return this.cityField;
            }
            set {
                this.cityField = value;
                this.RaisePropertyChanged("city");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, DataType="base64Binary", Order=1)]
        public byte[] cinIcon {
            get {
                return this.cinIconField;
            }
            set {
                this.cinIconField = value;
                this.RaisePropertyChanged("cinIcon");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public string cinAddress {
            get {
                return this.cinAddressField;
            }
            set {
                this.cinAddressField = value;
                this.RaisePropertyChanged("cinAddress");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("halls", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=3)]
        public hall[] halls {
            get {
                return this.hallsField;
            }
            set {
                this.hallsField = value;
                this.RaisePropertyChanged("halls");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class hall : baseModel {
        
        private section[] sectionsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("sections", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=0)]
        public section[] sections {
            get {
                return this.sectionsField;
            }
            set {
                this.sectionsField = value;
                this.RaisePropertyChanged("sections");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class section : baseModel {
        
        private decimal secCoefField;
        
        private bool secCoefFieldSpecified;
        
        private seat[] seatsField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal secCoef {
            get {
                return this.secCoefField;
            }
            set {
                this.secCoefField = value;
                this.RaisePropertyChanged("secCoef");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool secCoefSpecified {
            get {
                return this.secCoefFieldSpecified;
            }
            set {
                this.secCoefFieldSpecified = value;
                this.RaisePropertyChanged("secCoefSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute("seats", Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true, Order=1)]
        public seat[] seats {
            get {
                return this.seatsField;
            }
            set {
                this.seatsField = value;
                this.RaisePropertyChanged("seats");
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class seat : baseModel {
        
        private bool seatIsactiveField;
        
        private int seatColumnField;
        
        private int seatNumField;
        
        private int seatRowField;
        
        private int seatTypeField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public bool seatIsactive {
            get {
                return this.seatIsactiveField;
            }
            set {
                this.seatIsactiveField = value;
                this.RaisePropertyChanged("seatIsactive");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public int seatColumn {
            get {
                return this.seatColumnField;
            }
            set {
                this.seatColumnField = value;
                this.RaisePropertyChanged("seatColumn");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public int seatNum {
            get {
                return this.seatNumField;
            }
            set {
                this.seatNumField = value;
                this.RaisePropertyChanged("seatNum");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=3)]
        public int seatRow {
            get {
                return this.seatRowField;
            }
            set {
                this.seatRowField = value;
                this.RaisePropertyChanged("seatRow");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=4)]
        public int seatType {
            get {
                return this.seatTypeField;
            }
            set {
                this.seatTypeField = value;
                this.RaisePropertyChanged("seatType");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(seat))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(section))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(hall))]
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(cinema))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class baseModel : object, System.ComponentModel.INotifyPropertyChanged {
        
        private decimal idField;
        
        private bool idFieldSpecified;
        
        private string nameField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public decimal id {
            get {
                return this.idField;
            }
            set {
                this.idField = value;
                this.RaisePropertyChanged("id");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlIgnoreAttribute()]
        public bool idSpecified {
            get {
                return this.idFieldSpecified;
            }
            set {
                this.idFieldSpecified = value;
                this.RaisePropertyChanged("idSpecified");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public string name {
            get {
                return this.nameField;
            }
            set {
                this.nameField = value;
                this.RaisePropertyChanged("name");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCinemas", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getCinemasRequest {
        
        public getCinemasRequest() {
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getCinemasResponse", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getCinemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema[] @return;
        
        public getCinemasResponse() {
        }
        
        public getCinemasResponse(EntertainmentNetwork.DAL.CinemaService.cinema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveCinemas", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveCinemasRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("arg0", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema[] arg0;
        
        public saveCinemasRequest() {
        }
        
        public saveCinemasRequest(EntertainmentNetwork.DAL.CinemaService.cinema[] arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="saveCinemasResponse", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class saveCinemasResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema[] @return;
        
        public saveCinemasResponse() {
        }
        
        public saveCinemasResponse(EntertainmentNetwork.DAL.CinemaService.cinema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCinemaById", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findCinemaByIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        public findCinemaByIdRequest() {
        }
        
        public findCinemaByIdRequest(decimal arg0) {
            this.arg0 = arg0;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="findCinemaByIdResponse", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class findCinemaByIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.cinema[] @return;
        
        public findCinemaByIdResponse() {
        }
        
        public findCinemaByIdResponse(EntertainmentNetwork.DAL.CinemaService.cinema[] @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateSeats", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class generateSeatsRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public decimal arg0;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg1;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int arg2;
        
        public generateSeatsRequest() {
        }
        
        public generateSeatsRequest(decimal arg0, int arg1, int arg2) {
            this.arg0 = arg0;
            this.arg1 = arg1;
            this.arg2 = arg2;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="generateSeatsResponse", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class generateSeatsResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.seat[] @return;
        
        public generateSeatsResponse() {
        }
        
        public generateSeatsResponse(EntertainmentNetwork.DAL.CinemaService.seat[] @return) {
            this.@return = @return;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public partial class immutableTriple : triple {
        
        private object leftField;
        
        private object middleField;
        
        private object rightField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public object left {
            get {
                return this.leftField;
            }
            set {
                this.leftField = value;
                this.RaisePropertyChanged("left");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=1)]
        public object middle {
            get {
                return this.middleField;
            }
            set {
                this.middleField = value;
                this.RaisePropertyChanged("middle");
            }
        }
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=2)]
        public object right {
            get {
                return this.rightField;
            }
            set {
                this.rightField = value;
                this.RaisePropertyChanged("right");
            }
        }
    }
    
    /// <remarks/>
    [System.Xml.Serialization.XmlIncludeAttribute(typeof(immutableTriple))]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.3752.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/")]
    public abstract partial class triple : object, System.ComponentModel.INotifyPropertyChanged {
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSimplifiedCinemasByCityIdShowId", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSimplifiedCinemasByCityIdShowIdRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> cityId;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, IsNullable=true)]
        public System.Nullable<decimal> showId;
        
        public getSimplifiedCinemasByCityIdShowIdRequest() {
        }
        
        public getSimplifiedCinemasByCityIdShowIdRequest(System.Nullable<decimal> cityId, System.Nullable<decimal> showId) {
            this.cityId = cityId;
            this.showId = showId;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="getSimplifiedCinemasByCityIdShowIdResponse", WrapperNamespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", IsWrapped=true)]
    public partial class getSimplifiedCinemasByCityIdShowIdResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://CinemaServices.Services.EntertainmentNetworkServer.ua.git.dev/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute("return", Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public EntertainmentNetwork.DAL.CinemaService.immutableTriple[] @return;
        
        public getSimplifiedCinemasByCityIdShowIdResponse() {
        }
        
        public getSimplifiedCinemasByCityIdShowIdResponse(EntertainmentNetwork.DAL.CinemaService.immutableTriple[] @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface CinemaServiceChannel : EntertainmentNetwork.DAL.CinemaService.CinemaService, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class CinemaServiceClient : System.ServiceModel.ClientBase<EntertainmentNetwork.DAL.CinemaService.CinemaService>, EntertainmentNetwork.DAL.CinemaService.CinemaService {
        
        public CinemaServiceClient() {
        }
        
        public CinemaServiceClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public CinemaServiceClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaServiceClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public CinemaServiceClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse EntertainmentNetwork.DAL.CinemaService.CinemaService.removeCinema(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request) {
            return base.Channel.removeCinema(request);
        }
        
        public void removeCinema(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest inValue = new EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).removeCinema(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse> EntertainmentNetwork.DAL.CinemaService.CinemaService.removeCinemaAsync(EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest request) {
            return base.Channel.removeCinemaAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.removeCinemaResponse> removeCinemaAsync(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest inValue = new EntertainmentNetwork.DAL.CinemaService.removeCinemaRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).removeCinemaAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.getCinemasResponse EntertainmentNetwork.DAL.CinemaService.CinemaService.getCinemas(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request) {
            return base.Channel.getCinemas(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema[] getCinemas() {
            EntertainmentNetwork.DAL.CinemaService.getCinemasRequest inValue = new EntertainmentNetwork.DAL.CinemaService.getCinemasRequest();
            EntertainmentNetwork.DAL.CinemaService.getCinemasResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).getCinemas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getCinemasResponse> EntertainmentNetwork.DAL.CinemaService.CinemaService.getCinemasAsync(EntertainmentNetwork.DAL.CinemaService.getCinemasRequest request) {
            return base.Channel.getCinemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getCinemasResponse> getCinemasAsync() {
            EntertainmentNetwork.DAL.CinemaService.getCinemasRequest inValue = new EntertainmentNetwork.DAL.CinemaService.getCinemasRequest();
            return ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).getCinemasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.saveCinemasResponse EntertainmentNetwork.DAL.CinemaService.CinemaService.saveCinemas(EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest request) {
            return base.Channel.saveCinemas(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema[] saveCinemas(EntertainmentNetwork.DAL.CinemaService.cinema[] arg0) {
            EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest inValue = new EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.saveCinemasResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).saveCinemas(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.saveCinemasResponse> EntertainmentNetwork.DAL.CinemaService.CinemaService.saveCinemasAsync(EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest request) {
            return base.Channel.saveCinemasAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.saveCinemasResponse> saveCinemasAsync(EntertainmentNetwork.DAL.CinemaService.cinema[] arg0) {
            EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest inValue = new EntertainmentNetwork.DAL.CinemaService.saveCinemasRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).saveCinemasAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse EntertainmentNetwork.DAL.CinemaService.CinemaService.findCinemaById(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request) {
            return base.Channel.findCinemaById(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.cinema[] findCinemaById(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest inValue = new EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest();
            inValue.arg0 = arg0;
            EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).findCinemaById(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse> EntertainmentNetwork.DAL.CinemaService.CinemaService.findCinemaByIdAsync(EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest request) {
            return base.Channel.findCinemaByIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.findCinemaByIdResponse> findCinemaByIdAsync(decimal arg0) {
            EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest inValue = new EntertainmentNetwork.DAL.CinemaService.findCinemaByIdRequest();
            inValue.arg0 = arg0;
            return ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).findCinemaByIdAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.generateSeatsResponse EntertainmentNetwork.DAL.CinemaService.CinemaService.generateSeats(EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest request) {
            return base.Channel.generateSeats(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.seat[] generateSeats(decimal arg0, int arg1, int arg2) {
            EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest inValue = new EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            EntertainmentNetwork.DAL.CinemaService.generateSeatsResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).generateSeats(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.generateSeatsResponse> EntertainmentNetwork.DAL.CinemaService.CinemaService.generateSeatsAsync(EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest request) {
            return base.Channel.generateSeatsAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.generateSeatsResponse> generateSeatsAsync(decimal arg0, int arg1, int arg2) {
            EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest inValue = new EntertainmentNetwork.DAL.CinemaService.generateSeatsRequest();
            inValue.arg0 = arg0;
            inValue.arg1 = arg1;
            inValue.arg2 = arg2;
            return ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).generateSeatsAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdResponse EntertainmentNetwork.DAL.CinemaService.CinemaService.getSimplifiedCinemasByCityIdShowId(EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest request) {
            return base.Channel.getSimplifiedCinemasByCityIdShowId(request);
        }
        
        public EntertainmentNetwork.DAL.CinemaService.immutableTriple[] getSimplifiedCinemasByCityIdShowId(System.Nullable<decimal> cityId, System.Nullable<decimal> showId) {
            EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest inValue = new EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest();
            inValue.cityId = cityId;
            inValue.showId = showId;
            EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdResponse retVal = ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).getSimplifiedCinemasByCityIdShowId(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdResponse> EntertainmentNetwork.DAL.CinemaService.CinemaService.getSimplifiedCinemasByCityIdShowIdAsync(EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest request) {
            return base.Channel.getSimplifiedCinemasByCityIdShowIdAsync(request);
        }
        
        public System.Threading.Tasks.Task<EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdResponse> getSimplifiedCinemasByCityIdShowIdAsync(System.Nullable<decimal> cityId, System.Nullable<decimal> showId) {
            EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest inValue = new EntertainmentNetwork.DAL.CinemaService.getSimplifiedCinemasByCityIdShowIdRequest();
            inValue.cityId = cityId;
            inValue.showId = showId;
            return ((EntertainmentNetwork.DAL.CinemaService.CinemaService)(this)).getSimplifiedCinemasByCityIdShowIdAsync(inValue);
        }
    }
}
